apiVersion: rottigni.tech/v1
kind: Scheduler
metadata:
  name: my-first-scheduler # A unique name for this specific Scheduler instance
  namespace: default      # The namespace where you want this Scheduler to operate
spec:
  schedules:
    - name: minutely-ping
      image: alpine/curl
      cronExpression: "*/1 * * * *" # Every minute
      params:
        - curl
        - "https://www.google.com"

    - name: env-variable-test # New scheduler entry
      image: busybox:latest  # A simple image to demonstrate env vars
      cronExpression: "*/2 * * * *" # Runs every 2 minutes
      params:
        - sh
        - -c
        - "echo 'Hello from ENVIRONMENT!'; echo 'MY_CUSTOM_VAR is: $MY_CUSTOM_VAR'; echo 'ANOTHER_SECRET_VAR is: $ANOTHER_SECRET_VAR'; sleep 5"
      env: # Environment variables for this job
        - name: MY_CUSTOM_VAR
          value: "This is a custom value!"
        - name: ANOTHER_SECRET_VAR
          value: "Shhh, this is a secret!"
        - name: POD_NAME
          valueFrom: # Example of getting a value from the Downward API
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace