apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rottigni.tech
  resources:
  - schedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rottigni.tech
  resources:
  - schedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - events
  verbs:
  - get
  - list
  - watch
