# This rule is not used by the project k8s-scheduler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over rottigni.tech.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-admin-role
rules:
- apiGroups:
  - rottigni.tech
  resources:
  - schedulers
  verbs:
  - '*'
- apiGroups:
  - rottigni.tech
  resources:
  - schedulers/status
  verbs:
  - get
