apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-cj-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-admin-role
rules:
- apiGroups:
  - lr.labs
  resources:
  - schedulers
  verbs:
  - '*'
- apiGroups:
  - lr.labs
  resources:
  - schedulers/status
  verbs:
  - get
  - update
  - patch
