# This rule is not used by the project k8s-scheduler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to scheduling.deesup.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-viewer-role
rules:
- apiGroups:
  - scheduling.deesup.com
  resources:
  - schedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.deesup.com
  resources:
  - schedulers/status
  verbs:
  - get
