apiVersion: lr.labs/v1
kind: Scheduler
metadata:
  labels:
    app.kubernetes.io/name: k8s-cj-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: scheduler-sample
spec:
  # TODO(user): Add fields here
